package com.apteligent.display;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Created by levy on 7/19/16.
 */
public class BreadcrumbTrail {

    public enum BreadcrumbType {
        UNKNOWN, NORMAL, NETWORK_CALL, FOREGROUND_BACKGROUND, NETWORK_CONNECTION_CHANGE, VIEW_CHANGE, HANDLED_EXCEPTION, CRASH
    }

    public static class Breadcrumb {
        String deviceOccurredTs;
        String type;
        LinkedHashMap<String, String> payload; // {"priority":"normal","text":"MenuControlAcivity: rateAppDialogCallback()"}
        BreadcrumbType typeCode; // type of breadcrumb
        @Override
        public String toString() {
            // build payload
            String payloadJson = "{";
            for (Map.Entry<String, String> entry : payload.entrySet()) {
                payloadJson += "\"" + entry.getKey() + "\":\"" + entry.getValue() + "\",";
            }
            payloadJson = payloadJson.substring(0, payloadJson.length()-1); // remove trailing comma
            payloadJson += "}";
            return String.format("{\"deviceOccurredTs\":\"%s\",\"type\":\"%s\",\"payload\":%s,\"typeCode\":%d}",
                                deviceOccurredTs, type, payloadJson, typeCode.ordinal());
        }
    }

    String username;
    String traceTs;  // ex: "2016-07-10T07:33:27.924+00:00"
    ArrayList<Breadcrumb> parsedBreadcrumbs;
    String appVersion;
    String deviceId; // randomly generated by Apteligent
    String device;
    String os;

    /*
        Spits out valid json string
     */
    @Override
    public String toString() {
        String breadcrumbs = "[]";
        if (parsedBreadcrumbs != null && parsedBreadcrumbs.size() > 0) {
            breadcrumbs = "[";
            for(int i = 0; i < parsedBreadcrumbs.size(); i++) {
                breadcrumbs += parsedBreadcrumbs.get(i).toString();
                if(i != parsedBreadcrumbs.size() - 1) {
                    breadcrumbs += ",";
                }
            }
            breadcrumbs += "]";
        }
        return String.format("{\"username\":\"%s\",\"traceTs\":\"%s\",\"appVersion\":\"%s\",\"deviceId\":\"%s\"" +
                        ",\"device\":\"%s\",\"os\":\"%s\",\"parsedBreadcrumbs\":%s}",
                username, traceTs, appVersion, deviceId, device, os, breadcrumbs);
    }
}
